/**
 * Created by TC on 09/10/2022.
 */

object Libs {
    const val ACTIVITY_COMPOSE = "androidx.activity:activity-compose"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val CAMERAX_CORE = "androidx.camera:camera-camera2"
    const val CAMERAX_LIFECYCLE = "androidx.camera:camera-lifecycle"
    const val CAMERAX_VIEW = "androidx.camera:camera-view"
    const val COIL_BASE = "io.coil-kt:coil-base"
    const val COIL_COMPOSE = "io.coil-kt:coil-compose"
    const val COMPOSE_LIVE_DATA = "androidx.compose.runtime:runtime-livedata"
    const val COMPOSE_MATERIAL = "androidx.compose.material:material"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_TEST = "androidx.compose.ui:ui-test-junit4"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling"
    const val COMPOSE_UI_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview"
    const val COMPRESSOR = "id.zelory:compressor"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val CORE_SPLASH_SCREEN = "androidx.core:core-splashscreen"
    const val DATA_STORE_PREFERENCES = "androidx.datastore:datastore-preferences"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val GOOGLE_SERVICES_AUTH = "com.google.android.gms:play-services-auth"
    const val GSON = "com.google.code.gson:gson"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_NAVIGATION_COMPOSE = "androidx.hilt:hilt-navigation-compose"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing"
    const val JUNIT = "junit:junit"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler"
    const val LIFECYCLE_VIEW_MODEL_COMPOSE = "androidx.lifecycle:lifecycle-viewmodel-compose"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val MATERIAL_ICONS_EXTENDED = "androidx.compose.material:material-icons-extended"
    const val NAVIGATION_COMPOSE = "androidx.navigation:navigation-compose"
    const val OKHTTP_LOGGING = "com.squareup.okhttp3:logging-interceptor"
    const val PAGER = "com.google.accompanist:accompanist-pager"
    const val PAGING = "androidx.paging:paging-runtime"
    const val PAGING_COMPOSE = "androidx.paging:paging-compose"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_CONVERTER = "com.squareup.retrofit2:converter-gson"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_PAGING = "androidx.room:room-paging"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val SWIPE_REFRESH = "com.google.accompanist:accompanist-swiperefresh"
    const val TIMBER = "com.jakewharton.timber:timber"
}